services:
  finparser:
    container_name: finparser
    image: golovkov/finparser:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - fin-network


networks:
  fin-network:
    external: true